#!/usr/bin/env ruby

environment_tag = ARGV[0]&.strip

if environment_tag.nil? || environment_tag.empty?
  puts "Usage: deliver-deployed-stories ENVIRONMENT"
  exit 1
end

puts `bin/story-ids-deployed #{environment_tag} | bin/get-story-info-from-id | bin/deliver-story`
