#!/usr/bin/env ruby

environment_tag = ARGV[0]&.strip

if environment_tag.nil? || environment_tag.empty?
  puts "Usage: deliver-deployed-stories ENVIRONMENT"
  exit 1
end

puts `story-ids-deployed #{environment_tag} | get-story-info-from-id | deliver-story`
