#!/usr/bin/env ruby

tag = ARGV[0]&.strip

if tag.nil?
  puts "No tag given!!"
  exit 1
end

latest_sha = `git log --no-walk --tags=#{tag} -1 --pretty=oneline | awk '{print $1}'`
exit 1 if latest_sha.strip.empty?

puts latest_sha
exit 0

