#!/usr/bin/env ruby

require_relative '../lib/pivotoolz/git_branch'

if ARGV.length < 1
  puts "#{GitBranch.usage_message}"
  exit
end
first_arg, *the_rest = ARGV
puts GitBranch.new.generate(first_arg, the_rest)
